### ISSUE TITLE
Did i miss something or is the example not working?

### ISSUE THREAD

**Issue by SpazeDev** [TeamSpeak-Systems/ts3_sdk_dotNet#4]
Hey,

i just downloaded the this repo and the latest sdk (3.0.4.4) and the latest server (3.3.0), removed the password (https://github.com/TeamSpeak-Systems/ts3_sdk_dotNet/blob/master/examples/Client/Program.cs#L71) and tried to start the example.
But all i get is an FailedConnectionInitialisation at (https://github.com/TeamSpeak-Systems/ts3_sdk_dotNet/blob/master/examples/Client/Program.cs#L84).

Is this sdk no longer maintained because you are working on Teamspeak 5 or do i have to do something different?
And by the way: Will Teamspeak 5 also have and sdk?

**Comment by muenchow** [comment]
The SDK can only connect to a SDK-Server. You can find a simple example server in the 'server' directory inside the sdk folder. More information about the SDK-Server can be found in the full sdk's documentation.
There is currently no c#-wrapper for the sdk server.
As for TeamSpeak 5: A TeamSpeak 5-Client will be able to connect to a TeamSpeak 3-Server.
